// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qCIAFpiwykNzyb3t5Uuqfukh3fuRCKA',
    appId: '1:864243999965:web:396bc4d18e97819bafa734',
    messagingSenderId: '864243999965',
    projectId: 'aulaspdm-fa6c2',
    authDomain: 'aulaspdm-fa6c2.firebaseapp.com',
    storageBucket: 'aulaspdm-fa6c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwIfFJpijNs3GWkOhgY1Et6AdVTS6OAqs',
    appId: '1:864243999965:android:50233b2ad12291fcafa734',
    messagingSenderId: '864243999965',
    projectId: 'aulaspdm-fa6c2',
    storageBucket: 'aulaspdm-fa6c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjucdrWDnS62Q1sJozbm6hWuaKXvdNnMM',
    appId: '1:864243999965:ios:54cd36e07770a00bafa734',
    messagingSenderId: '864243999965',
    projectId: 'aulaspdm-fa6c2',
    storageBucket: 'aulaspdm-fa6c2.firebasestorage.app',
    iosBundleId: 'com.example.aulaspdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjucdrWDnS62Q1sJozbm6hWuaKXvdNnMM',
    appId: '1:864243999965:ios:54cd36e07770a00bafa734',
    messagingSenderId: '864243999965',
    projectId: 'aulaspdm-fa6c2',
    storageBucket: 'aulaspdm-fa6c2.firebasestorage.app',
    iosBundleId: 'com.example.aulaspdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7qCIAFpiwykNzyb3t5Uuqfukh3fuRCKA',
    appId: '1:864243999965:web:52ce7cc97dc45bc1afa734',
    messagingSenderId: '864243999965',
    projectId: 'aulaspdm-fa6c2',
    authDomain: 'aulaspdm-fa6c2.firebaseapp.com',
    storageBucket: 'aulaspdm-fa6c2.firebasestorage.app',
  );
}
